apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    prometheus.io/scrape: "true"  # Tells Prometheus to scrape metrics
    prometheus.io/port: "80"    # Port on which Nexus exposes metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80  # Expose Prometheus metrics on this port
