apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scaledobject
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: nginx
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod:  10   # Optional: how long to wait before scaling down
  pollingInterval: 20   # Optional: check every 30 seconds
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.default.svc.cluster.local:80
      metricName: nginx_cpu_usage_percentage
      query: |
        sum(rate(container_cpu_usage_seconds_total{namespace="ns-apps", pod=~"nginx-.*"}[3m])) / count(rate(container_cpu_usage_seconds_total{namespace="ns-apps", pod=~"nginx-.*"}[3m])) * 100
      threshold: "2.0"
