apiVersion: v2
name: keda
description: A Helm chart for deploying KEDA autoscaling
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: keda
    version: "2.14.2" # or latest version from KEDA Helm repo
    repository: "https://kedacore.github.io/charts"

