name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  pre-requisites:
    runs-on: self-hosted
    steps:
      - name: install kubectl
        uses: azure/setup-kubectl@v4
        with:
           version: '1.32.0'
        id: install
            
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubeconfig
        if: success()
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $GITHUB_WORKSPACE/kubeconfig

      - name: Show cluster info
        if: success()
        run: |
          kubectl config get-contexts
          kubectl get nodes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
