name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  pre-requisites:
    runs-on: self-hosted
    steps:
      - name: install kubectl
        uses: azure/setup-kubectl@v4
        with:
           version: 'v1.32.0'
        id: install-kubectl

      - name: install helm
        uses: azure/setup-helm@v4.3.0
        with:
           version: 'v3.16.4' # default is latest (stable)
        id: install-helm
            
  deploy:
    needs: pre-requisites
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubeconfig
        if: success()
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $GITHUB_WORKSPACE/kubeconfig

      - name: Show cluster info
        if: success()
        run: |
          kubectl config get-contexts
          kubectl get nodes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
