name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $GITHUB_WORKSPACE/kubeconfig
          export KUBECONFIG=${{ github.workspace }}/kubeconfig

      - name: Show cluster info
        run: |
          kubectl config get-contexts
          kubectl get nodes
